language: php

php:
  - 5.5
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300

before_script: mkdir -p build/logs

install: composer install --no-interaction

after_script: if [ $(phpenv version-name) = "5.6" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi
