language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly

before_script: mkdir -p build/logs
install: composer install --no-interaction
after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
